version: 2
project_name: name
before:
  hooks:
    - go mod download

builds:
  - id: client
    dir: .
    main: .
    binary: name
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

release:
  prerelease: true

archives:
  - wrap_in_directory: true
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
